# Generated by Django 5.0.6 on 2024-05-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
                ('loan_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
            ],
        ),
    ]
